### ISSUE TITLE
Create Window of Music player

### ISSUE THREAD

**Issue by gakushibata** [gakushibata/hello-github#2]
#1 ToDo
- [x] implement functions into the player
- [ ] add UI materials
- [ ] put UI components
- [ ] TEST

#参考資料
[Apple Music Player](https://www.apple.com/jp/music/)
